# Generated by Django 3.2.7 on 2021-10-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, default='https://cdn.pixabay.com/photo/2017/06/30/10/14/social-media-2457842_1280.png', upload_to='user_profile/'),
        ),
    ]
