# Generated by Django 3.2.7 on 2021-10-17 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticketitem',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
