# Generated by Django 3.2.7 on 2021-10-12 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tickets_available',
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='num_of_childen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_num_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
