# Generated by Django 3.2.7 on 2021-09-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/categories')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('short_description', models.TextField(help_text='Enter a short descriptionmax 150 characters', max_length=150)),
                ('full_description', models.TextField(max_length=800)),
                ('included', models.TextField(blank=True, max_length=800)),
                ('what_to_bring', models.TextField(blank=True, max_length=800)),
                ('duration', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('departure_location', models.TextField(max_length=800)),
                ('family_friendly', models.BooleanField(default=True)),
                ('add_to_favourites', models.BooleanField(blank=True, default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('images', models.ImageField(upload_to='media')),
                ('days_available', models.DateField()),
                ('num_tickets', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.category')),
            ],
        ),
    ]
