# Generated by Django 3.2.7 on 2021-09-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='days_available',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='price',
        ),
        migrations.AddField(
            model_name='trip',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='trip',
            name='child_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='trip',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='trip',
            name='special_offer',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='short_description',
            field=models.TextField(help_text='Enter a short descriptionmax 150 characters', max_length=300),
        ),
        # migrations.AlterField(
        #     model_name='trip',
        #     name='start_time',
        #     field=models.TimeField(default=True),
        # ),
    ]
