# Generated by Django 3.2.7 on 2021-09-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20210917_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to='media/categories'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='images',
            field=models.ImageField(upload_to='media/trips'),
        ),
    ]
