# Generated by Django 3.2.7 on 2021-09-30 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20210917_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trip',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        # migrations.AlterField(
        #     model_name='trip',
        #     name='start_time',
        #     field=models.TimeField(),
        # ),
    ]
