# Generated by Django 3.2.7 on 2021-10-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20210930_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.CharField(choices=[('6 AM', '6 AM'), ('7 AM', '7 AM'), ('8 AM', '8 AM'), ('9 AM', '9 AM'), ('10 AM', '10 AM'), ('12 PM', '12 PM'), ('1 PM', '1 PM'), ('6 PM', '6 PM')], default='8AM', max_length=5),
        ),
    ]
