# Generated by Django 3.2.7 on 2021-11-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20211027_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.CharField(choices=[('6 AM', '06:00'), ('7 AM', '07:00'), ('8 AM', '08:00'), ('9 AM', '09:00'), ('10 AM', '10:00'), ('12 PM', '12:00'), ('1 PM', '13:00'), ('6 PM', '18:00')], default='8AM', max_length=5),
        ),
    ]
