# Generated by Django 3.2.7 on 2021-11-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_trip_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.CharField(choices=[('06:00', '06:00'), ('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('18:00', '18:00')], default='8AM', max_length=5),
        ),
    ]
