# Generated by Django 3.2.7 on 2021-11-11 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_alter_reviewrating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='review',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='trip',
            name='short_description',
            field=models.TextField(help_text='Enter a short descriptionmax 300 characters', max_length=300),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.CharField(choices=[('06:00', '06:00'), ('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('18:00', '18:00')], default='08:00', max_length=5),
        ),
    ]
